# Generated by Django 2.2.10 on 2020-03-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
