# Generated by Django 2.2.10 on 2020-03-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200328_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-1'),
            preserve_default=False,
        ),
    ]
