# Generated by Django 3.0.4 on 2020-04-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
