# Generated by Django 3.0.4 on 2020-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='owner/images'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
