# Generated by Django 3.0.4 on 2020-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200420_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='AddedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
