# Generated by Django 3.0.4 on 2020-05-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_orderitem_addeddate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='AddedDate',
            field=models.DateTimeField(default='2020-03-25'),
            preserve_default=False,
        ),
    ]
