# Generated by Django 3.0.8 on 2020-07-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200518_1939'),
    ]

    operations = [

        migrations.AddField(
            model_name='refund',
            name='date',
            field=models.DateField(auto_now_add=True, default='2020-07-24'),
            preserve_default=False,
        ),
        
    ]
